index:
    path: /{page}
    defaults: { _controller: 'App\Controller\IndexController::index' }

githubHook:
    path: /github_webhook
    defaults: { _controller: 'App\Controller\GithubController::githubHook' }